### ISSUE TITLE
Suspensión not working on UNMS 1.0.4

### ISSUE THREAD

**Issue by gustavo2147** [Ubiquiti-App/UCRM-plugins#159]
it was working very very fine in the previous version, and now is not working anymore

**Comment by keksa** [comment]
Hello @gustavo2147, thank you for the report, we know about the problem and are working on fix.

**Comment by keksa** [comment]
Hello @gustavo2147, this problem has been fixed in UCRM 2.16.8 and UNMS 1.0.5, please upgrade.
