### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by rspaeth79** [Ubiquiti-App/UCRM-plugins#162]
Any chance someone on the team can compile a table of the different links to the Apiary Docs for each version.  And then maybe include it in the README.md?

So far, there are the following I have found at docs.apiary.io:
- unmscrm
- ucrmbeta
- ucrmdev
- ucrm

I am currently referencing multiples of the above while coding against UCRM 3.1.0-beta1 and not sure which should be the correct docs.

Much appreciated.

**Comment by UBNT-Petr** [comment]
Hi @rspaeth79 we have updated the API guide with all the links needed: https://help.ubnt.com/hc/en-us/articles/115003906007-UCRM-API-Usage#document

(the dev documentation is not mentioned, as it is used only for internal purposes. However, if you want some insight into the upcoming API for the currently developing CRM version, you can follow: https://ucrmdev.docs.apiary.io
