### ISSUE TITLE
No Account Numbers in Quickbooks

### ISSUE THREAD

**Issue by nzrunner** [Ubiquiti-App/UCRM-plugins#31]
My Quickbooks does not use Account Numbers, the accounts only have a name.

How do I assign the Income Account Number in the Plugin setup if I have no Account Numbers in Quickbooks?

Note, my customers are syncing nicely :-)

**Comment by ryanww** [comment]
I was able to find this by going into the API explorer, then ender account - typed in "select * from Item" for query and found the correct ID.

Now I'm trying to figure out this thing further. I have an existing client in my QB file. How do I connect that? Its the same name?

> [2018-07-25 18:05:01.645107] [info] Invoice ID: 5 needs to be exported
> [2018-07-25 18:05:02.638551] [error] Client with Display name containing: UCRMID-1 is not found
> [2018-07-25 18:05:02.638624] [info] CLI process ended
> [2018-07-25 18:09:01.337630] [info] CLI process started
> [2018-07-25 18:09:02.106937] [info] Client ID: 2 needs to be exported
> [2018-07-25 18:09:02.570012] [info] Client NSAV (ID: 2) export failed.
> [2018-07-25 18:09:02.570120] [error] Client NSAV (ID: 2) export failed with error It is not possible to parse QB error: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
> <IntuitResponse time="2018-07-25T11:09:02.260-07:00" xmlns="http://schema.intuit.com/finance/v3">
>     <Fault type="SERVICE">
>         <Error code="3100">
>             <Message>message=AuthorizationFailed; errorCode=003100; statusCode=403</Message>
>         </Error>
>     </Fault>
> </IntuitResponse>
> .
> [2018-07-25 18:09:02.670780] [info] Invoice ID: 5 needs to be exported
> [2018-07-25 18:09:03.002093] [error] Client with Display name containing: UCRMID-1 is not found
> [2018-07-25 18:09:03.002146] [info] Invoice ID: 6 needs to be exported
> [2018-07-25 18:09:06.487426] [error] Client with Display name containing: UCRMID-2 is not found
> [2018-07-25 18:09:06.487504] [info] CLI process ended

**Comment by raymondjclark** [comment]
Many changes have been made, please try the latest release.
