### ISSUE TITLE
All invoices syncing as $1 to QB.

### ISSUE THREAD

**Issue by MaximLevtov** [Ubiquiti-App/UCRM-plugins#42]
Hey,

For some reason all invoices that get synced over are coming up in QB as $1.00. Everything else is correct.

**Comment by raymondjclark** [comment]
I updated line 248 in QuickBooksFacade.php to change $item['quantity'] to $item['price'] and the invoices are going over to QB with the correct price. I don't know how to make the change here in github

**Comment by UBNT-Petr** [comment]
fixed in QB Plugin v1.0.6
